"""temp_migration

Revision ID: f6ef8a9c16f2
Revises: ff68cb4dad2a
Create Date: 2025-12-18 17:24:23.858136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6ef8a9c16f2'
down_revision: Union[str, Sequence[str], None] = 'ff68cb4dad2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'successful', 'canceled', 'refunded', name='paymentstatusenum'),
               server_default='pending',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'successful', 'canceled', 'refunded', name='paymentstatusenum'),
               server_default=sa.text("'successful'::paymentstatusenum"),
               existing_nullable=False)
    # ### end Alembic commands ###
